# -*- coding: utf-8 -*-
"""Flow_Network_Model_MDPI (Final).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U7yIYePK-nNto5Eo2EGScyxaFXe5vkVm
"""

# @title Simulation Systemic Risk - MDPI Publication Quality -*- coding: utf-8 -*-

from itertools import permutations
import matplotlib.pyplot as plt
from time import process_time as ptime
import numpy as np
import pandas as pd

# ➕➕➕ IMPORTS FOR PUBLICATION-QUALITY FIGURES ➕➕➕
import seaborn as sns
import matplotlib as mpl
from matplotlib import rcParams

# ============================================================================
# PUBLICATION STYLE CONFIGURATION (LaTeX Beamer Academic Presentation Style)
# ============================================================================

# Font Configuration - LaTeX Academic Style
rcParams['font.family'] = 'serif'
rcParams['font.serif'] = ['Computer Modern Roman', 'Times New Roman', 'DejaVu Serif']
rcParams['font.size'] = 10
rcParams['axes.labelsize'] = 12
rcParams['axes.titlesize'] = 13
rcParams['xtick.labelsize'] = 10
rcParams['ytick.labelsize'] = 10
rcParams['legend.fontsize'] = 10
rcParams['figure.titlesize'] = 14
rcParams['text.usetex'] = False  # Set to True if LaTeX is installed
rcParams['mathtext.fontset'] = 'cm'  # Computer Modern math fonts

# Line and Border Configuration - Clean Professional Style
rcParams['axes.linewidth'] = 1.5
rcParams['grid.linewidth'] = 0.8
rcParams['lines.linewidth'] = 2.0
rcParams['patch.linewidth'] = 1.5

# Color Configuration - All text BLACK
rcParams['text.color'] = 'black'
rcParams['axes.labelcolor'] = 'black'
rcParams['xtick.color'] = 'black'
rcParams['ytick.color'] = 'black'
rcParams['axes.edgecolor'] = 'black'

# Grid Configuration - Subtle grey
rcParams['grid.color'] = '#CCCCCC'
rcParams['grid.alpha'] = 0.3
rcParams['grid.linestyle'] = '--'

# Figure Configuration - High quality for MDPI
rcParams['figure.dpi'] = 600  # MDPI requirement: ≥600 dpi
rcParams['savefig.dpi'] = 600
rcParams['savefig.bbox'] = 'tight'
rcParams['savefig.facecolor'] = 'white'
rcParams['savefig.edgecolor'] = 'none'
rcParams['savefig.format'] = 'png'

# LaTeX Beamer Color Palette (Academic Presentation Style)
# Based on classic beamer themes: blues, greys, professional
colors = {
    'beamer_blue': '#003366',      # Dark navy blue (primary)
    'beamer_light_blue': '#4682B4', # Steel blue (secondary)
    'beamer_grey': '#707070',       # Medium grey
    'beamer_light_grey': '#B0B0B0', # Light grey
    'beamer_dark_grey': '#404040',  # Dark grey
    'accent_blue': '#5F84A2',       # Accent blue-grey
    'background': '#F5F5F5',        # Off-white background
    'grid': '#CCCCCC',              # Grid color
    'text': '#000000'               # All text: BLACK
}

# Corporate Finance Color Palette (Professional Gradient)
# For bar charts and categorical data
corporate_palette = {
    'stable': '#E0E7ED',      # Very light blue-grey (low risk)
    'low': '#A8BDCC',         # Light blue-grey
    'medium': '#5F84A2',      # Medium slate blue
    'elevated': '#2E5A7D',    # Deep blue-grey
    'critical': '#1A3A52'     # Dark navy (high risk)
}

# ============================================================================
# HELPER FUNCTION: EXTRACT QUARTER RESULTS
# ============================================================================

def extract_quarter_results(E, H, PH, count, quarter_name):
    """
    Extract all statistics for one quarter

    Parameters:
    -----------
    E : list
        Equity losses for all scenarios
    H : list
        External debt losses for all scenarios
    PH : list
        Bank failure counts [P(0), P(1), P(2), P(3), P(4)]
    count : int
        Total number of scenarios
    quarter_name : str
        Quarter label (e.g., 'Q1 2009')

    Returns:
    --------
    dict
        Dictionary containing all summary statistics
    """
    E_arr = np.array(E)
    H_arr = np.array(H)
    SR_arr = E_arr + H_arr

    return {
        'Quarter': quarter_name,
        'Mean_E': np.mean(E_arr),
        'Min_E': np.min(E_arr),
        'Max_E': np.max(E_arr),
        'Mean_H': np.mean(H_arr),
        'Min_H': np.min(H_arr),
        'Max_H': np.max(H_arr),
        'Mean_SR': np.mean(SR_arr),
        'Min_SR': np.min(SR_arr),
        'Max_SR': np.max(SR_arr),
        'Std_SR': np.std(SR_arr),
        'P_0_banks': PH[0] / count,
        'P_1_bank': PH[1] / count,
        'P_2_banks': PH[2] / count,
        'P_3_banks': PH[3] / count,
        'P_4_banks': PH[4] / count,
        'P_at_least_1': 1 - (PH[0] / count),
        'P_at_least_2': 1 - (PH[0] + PH[1]) / count,
        'Expected_failures': sum(i * PH[i] / count for i in range(5)),
        'Equity_share': np.mean(E_arr) / np.mean(SR_arr) if np.mean(SR_arr) > 0 else 0,
        'Ext_debt_share': np.mean(H_arr) / np.mean(SR_arr) if np.mean(SR_arr) > 0 else 0,
        'N_scenarios': count
    }

# ============================================================================
# PUBLICATION FIGURE CREATION FUNCTION (LaTeX Beamer Style)
# ============================================================================

def create_publication_figures(E, H, PH, count, quarter_label, quarter_name):
    """
    Create publication-quality figures in LaTeX Beamer academic style

    MDPI Requirements:
    - Resolution: 600+ dpi ✓
    - Format: PNG, TIFF ✓
    - Color: RGB 8-bit ✓
    - Fonts: All BLACK ✓
    - Style: Professional academic ✓

    Parameters:
    -----------
    E : list
        Equity losses (millions USD)
    H : list
        External debt losses (millions USD)
    PH : list
        Bank failure probability histogram
    count : int
        Total scenarios
    quarter_label : str
        File name label (e.g., 'Q1_2009')
    quarter_name : str
        Display name (e.g., 'Q1 2009')
    """

    # Convert to numpy arrays (values in MILLIONS USD)
    E_arr = np.array(E)
    H_arr = np.array(H)
    SR_arr = E_arr + H_arr

    print(f"\n{'='*80}")
    print(f"Creating publication figures for {quarter_name}")
    print(f"{'='*80}")
    print(f"Equity (E):        min=${min(E_arr):>12,.0f}M  max=${max(E_arr):>12,.0f}M  mean=${np.mean(E_arr):>12,.0f}M")
    print(f"Ext. Debt (H):     min=${min(H_arr):>12,.0f}M  max=${max(H_arr):>12,.0f}M  mean=${np.mean(H_arr):>12,.0f}M")
    print(f"Systemic Risk (SR): min=${min(SR_arr):>12,.0f}M  max=${max(SR_arr):>12,.0f}M  mean=${np.mean(SR_arr):>12,.0f}M")
    print(f"Scenarios: {count:,}")

    # ========================================================================
    # FIGURE 1: EQUITY LOSS DISTRIBUTION (Grey-Blue Academic Style)
    # ========================================================================

    fig = plt.figure(figsize=(8, 6), dpi=600, facecolor='white')
    ax = fig.add_subplot(111)

    # Histogram with professional blue-grey color
    counts, bins, patches = ax.hist(E_arr, bins=50, density=True,
                                     color=colors['beamer_light_blue'],
                                     alpha=0.75,
                                     edgecolor='black', linewidth=1.0)

    # All labels in BLACK
    ax.set_xlabel('Equity Loss (Millions USD)', fontsize=12, fontweight='bold', color='black')
    ax.set_ylabel('Probability Density', fontsize=12, fontweight='bold', color='black')
    ax.set_title(f'Distribution of Equity Losses\n{quarter_name}',
                 fontsize=14, fontweight='bold', color='black', pad=15)

    # Grid - subtle grey
    ax.grid(True, alpha=0.3, linestyle='--', color='#CCCCCC', linewidth=0.8)
    ax.set_axisbelow(True)

    # Mean line - dark blue
    mean_E = np.mean(E_arr)
    ax.axvline(mean_E, color=colors['beamer_blue'], linestyle='--', linewidth=2.5,
               label=f'Mean: ${mean_E:,.0f}M', alpha=0.9)

    # Legend with BLACK text
    legend = ax.legend(loc='upper right', fontsize=10, frameon=True,
                      shadow=True, fancybox=True)
    plt.setp(legend.get_texts(), color='black')

    # Tick parameters - BLACK
    ax.tick_params(axis='both', colors='black', labelsize=10)

    # Spine configuration - BLACK
    for spine in ax.spines.values():
        spine.set_edgecolor('black')
        spine.set_linewidth(1.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig(f'Fig_Equity_{quarter_label}.png', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.savefig(f'Fig_Equity_{quarter_label}.tiff', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    print(f"  ✓ Saved Fig_Equity_{quarter_label}.png (600 dpi)")

    # ========================================================================
    # FIGURE 2: EXTERNAL DEBT LOSS DISTRIBUTION (Grey-Blue Academic Style)
    # ========================================================================

    fig = plt.figure(figsize=(8, 6), dpi=600, facecolor='white')
    ax = fig.add_subplot(111)

    # Histogram with professional grey color
    counts, bins, patches = ax.hist(H_arr, bins=50, density=True,
                                     color=colors['beamer_grey'],
                                     alpha=0.75,
                                     edgecolor='black', linewidth=1.0)

    # All labels in BLACK
    ax.set_xlabel('External Debt Loss (Millions USD)', fontsize=12, fontweight='bold', color='black')
    ax.set_ylabel('Probability Density', fontsize=12, fontweight='bold', color='black')
    ax.set_title(f'Distribution of External Debt Losses\n{quarter_name}',
                 fontsize=14, fontweight='bold', color='black', pad=15)

    # Grid - subtle grey
    ax.grid(True, alpha=0.3, linestyle='--', color='#CCCCCC', linewidth=0.8)
    ax.set_axisbelow(True)

    # Mean line - dark blue
    mean_H = np.mean(H_arr)
    ax.axvline(mean_H, color=colors['beamer_blue'], linestyle='--', linewidth=2.5,
               label=f'Mean: ${mean_H:,.0f}M', alpha=0.9)

    # Legend with BLACK text
    legend = ax.legend(loc='upper right', fontsize=10, frameon=True,
                      shadow=True, fancybox=True)
    plt.setp(legend.get_texts(), color='black')

    # Tick parameters - BLACK
    ax.tick_params(axis='both', colors='black', labelsize=10)

    # Spine configuration - BLACK
    for spine in ax.spines.values():
        spine.set_edgecolor('black')
        spine.set_linewidth(1.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig(f'Fig_ExtDebt_{quarter_label}.png', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.savefig(f'Fig_ExtDebt_{quarter_label}.tiff', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    print(f"  ✓ Saved Fig_ExtDebt_{quarter_label}.png (600 dpi)")

    # ========================================================================
    # FIGURE 3: TOTAL SYSTEMIC RISK DISTRIBUTION (Dark Blue Academic Style)
    # ========================================================================

    fig = plt.figure(figsize=(8, 6), dpi=600, facecolor='white')
    ax = fig.add_subplot(111)

    # Histogram with dark blue color
    counts, bins, patches = ax.hist(SR_arr, bins=50, density=True,
                                     color=colors['beamer_blue'],
                                     alpha=0.70,
                                     edgecolor='black', linewidth=1.0)

    # All labels in BLACK
    ax.set_xlabel('Total Systemic Risk (Millions USD)', fontsize=12, fontweight='bold', color='black')
    ax.set_ylabel('Probability Density', fontsize=12, fontweight='bold', color='black')
    ax.set_title(f'Distribution of Total Systemic Risk (E+H)\n{quarter_name}',
                 fontsize=14, fontweight='bold', color='black', pad=15)

    # Grid - subtle grey
    ax.grid(True, alpha=0.3, linestyle='--', color='#CCCCCC', linewidth=0.8)
    ax.set_axisbelow(True)

    # Mean line - steel blue
    mean_SR = np.mean(SR_arr)
    ax.axvline(mean_SR, color=colors['beamer_light_blue'], linestyle='--', linewidth=2.5,
               label=f'Mean: ${mean_SR:,.0f}M', alpha=0.9)

    # Legend with BLACK text
    legend = ax.legend(loc='upper right', fontsize=10, frameon=True,
                      shadow=True, fancybox=True)
    plt.setp(legend.get_texts(), color='black')

    # Statistics text box - BLACK text on light background
    textstr = f'Mean: ${mean_SR:,.0f}M\nStd: ${np.std(SR_arr):,.0f}M\nN = {count:,}'
    props = dict(boxstyle='round,pad=0.5', facecolor='#E8EEF2',
                edgecolor='black', linewidth=1.5, alpha=0.9)
    ax.text(0.68, 0.97, textstr, transform=ax.transAxes, fontsize=10,
            verticalalignment='top', bbox=props, color='black', fontweight='bold')

    # Tick parameters - BLACK
    ax.tick_params(axis='both', colors='black', labelsize=10)

    # Spine configuration - BLACK
    for spine in ax.spines.values():
        spine.set_edgecolor('black')
        spine.set_linewidth(1.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig(f'Fig_SystRisk_{quarter_label}.png', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.savefig(f'Fig_SystRisk_{quarter_label}.tiff', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    print(f"  ✓ Saved Fig_SystRisk_{quarter_label}.png (600 dpi)")

    # ========================================================================
    # FIGURE 4: BANK FAILURE PROBABILITY (Corporate Blue-Grey Gradient)
    # ========================================================================

    fig = plt.figure(figsize=(8, 6), dpi=600, facecolor='white')
    ax = fig.add_subplot(111)

    x_pos = np.arange(5)
    probs = np.array(PH) / count

    # Corporate blue-grey gradient palette (LaTeX Beamer style)
    # Light grey → Dark navy blue (increasing severity)
    colors_bars = [
        corporate_palette['stable'],    # 0 banks: Very light blue-grey
        corporate_palette['low'],        # 1 bank: Light blue-grey
        corporate_palette['medium'],     # 2 banks: Medium slate blue
        corporate_palette['elevated'],   # 3 banks: Deep blue-grey
        corporate_palette['critical']    # 4 banks: Dark navy (critical)
    ]

    bars = ax.bar(x_pos, probs, width=0.65, color=colors_bars,
                  alpha=0.90, edgecolor='black', linewidth=1.8)

    # Add percentage labels - BLACK text
    for i, (bar, prob) in enumerate(zip(bars, probs)):
        height = bar.get_height()
        if height > 0.001:  # Only show if visible
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{prob*100:.2f}%',
                   ha='center', va='bottom', fontsize=11,
                   fontweight='bold', color='black')

    # All labels in BLACK
    ax.set_xlabel('Number of Banks Failed', fontsize=12, fontweight='bold', color='black')
    ax.set_ylabel('Probability', fontsize=12, fontweight='bold', color='black')
    ax.set_title(f'Bank Failure Probability Distribution\n{quarter_name}',
                 fontsize=14, fontweight='bold', color='black', pad=15)

    # X-axis configuration
    ax.set_xticks(x_pos)
    ax.set_xticklabels(['0', '1', '2', '3', '4'], fontsize=11, color='black')
    ax.set_ylim(0, max(probs) * 1.18)  # Add 18% space for labels

    # Format y-axis as percentage
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y*100:.0f}%'))

    # Grid - horizontal only, subtle grey
    ax.grid(True, alpha=0.3, linestyle='--', axis='y', color='#CCCCCC', linewidth=0.8)
    ax.set_axisbelow(True)

    # Tick parameters - BLACK
    ax.tick_params(axis='both', colors='black', labelsize=10)

    # Spine configuration - BLACK, minimal
    for spine in ax.spines.values():
        spine.set_edgecolor('black')
        spine.set_linewidth(1.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    plt.savefig(f'Fig_Failures_{quarter_label}.png', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.savefig(f'Fig_Failures_{quarter_label}.tiff', dpi=600, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    plt.close(fig)
    print(f"  ✓ Saved Fig_Failures_{quarter_label}.png (600 dpi)")

    print(f"{'='*80}")
    print(f"Completed all figures for {quarter_name}")
    print(f"{'='*80}\n")

# ============================================================================
# CONFIRMATION MESSAGE
# ============================================================================

print("\n" + "="*80)
print("✓✓✓ PUBLICATION-QUALITY FIGURE CONFIGURATION LOADED ✓✓✓")
print("="*80)
print("\nConfiguration:")
print("  • Style: LaTeX Beamer Academic Presentation")
print("  • Resolution: 600 DPI (MDPI compliant)")
print("  • Fonts: All BLACK, serif family")
print("  • Colors: Professional blue-grey gradient")
print("  • Format: PNG + TIFF dual export")
print("  • Grid: Subtle grey, academic style")
print("\nColor Palette:")
print(f"  • Primary: Dark Navy Blue ({colors['beamer_blue']})")
print(f"  • Secondary: Steel Blue ({colors['beamer_light_blue']})")
print(f"  • Tertiary: Medium Grey ({colors['beamer_grey']})")
print(f"  • All Text: BLACK ({colors['text']})")
print("\nCorporate Gradient (Bar Charts):")
print(f"  • 0 banks (stable):   Light grey-blue ({corporate_palette['stable']})")
print(f"  • 1 bank (low):       Light blue-grey ({corporate_palette['low']})")
print(f"  • 2 banks (medium):   Slate blue ({corporate_palette['medium']})")
print(f"  • 3 banks (elevated): Deep blue-grey ({corporate_palette['elevated']})")
print(f"  • 4 banks (critical): Dark navy ({corporate_palette['critical']})")
print("\nReady for simulation runs!")
print("="*80 + "\n")

# @title Initialize results list
all_quarterly_results = []

# @title Fill function

def fill(AR,AC,qt):
    if qt+AR[0]>AC[0]:
        qt2=qt+AR[0]-AC[0]
        AR[0]=AC[0]
        if qt2+AR[1]>AC[1]:
            qt3=qt2+AR[1]-AC[1]
            AR[1]=AC[1]
            AR[2]+=qt3
        else: AR[1]+=qt2
    else: AR[0]+=qt
    return AR

# @title Simulation main

A=ptime()
PMT=list(permutations([0, 1, 2,3]))
MC=[[144022,184133,774185],
    [166884,341254,1009277],
    [177052,92048,882997],
    [102316,49433,781402]]
T1R=[0,0,0]
T2R=[0,0,0]
T3R=[0,0,0]
T4R=[0,0,0]
E=[]
H=[]
PH=[0,0,0,0,0]
s=442000 #Shock
count=0
for c in range(len(PMT)):
    T1C=MC[PMT[c][0]]
    T2C=MC[PMT[c][1]]
    T3C=MC[PMT[c][2]]
    T4C=MC[PMT[c][3]]
    for i in range(1,26):
        for j in range(1,26-i):
            for l in range(1,26):
                for n in range(1,26):
                    T1R=[0,0,0]
                    T2R=[0,0,0]
                    T3R=[0,0,0]
                    T4R=[0,0,0]
                    T1R=fill(T1R,T1C,s) #Shock inicial
                    k=100-i-j
                    T2R=fill(T2R,T2C,T1R[1]*(i/100)) #Primera interacción
                    T3R=fill(T3R,T3C,T1R[1]*(j/100))
                    T4R=fill(T4R,T4C,T1R[1]*(k/100))
                    T1R[1]=0
                    m=100-l
                    T3R=fill(T3R,T3C,T2R[1]*(l/100)) #Segunda interacción
                    T4R=fill(T4R,T4C,T2R[1]*(m/100))
                    T2R[1]=0
                    T4R=fill(T4R,T4C,T3R[1]*(n/100)) #Tercera interacción
                    T3R[1]-=T3R[1]*(n/100)
                    count+=1
                    E.append(T1R[0]+T2R[0]+T3R[0]+T4R[0])
                    H.append(T1R[2]+T2R[2]+T3R[2]+T4R[2])
                    PH[4-[T1R[1],T2R[1],T3R[1],T4R[1]].count(0)]+=1
                    #print(sum(T1R)+sum(T2R)+sum(T3R)+sum(T4R)) #Debe ser siempre igual al shock
sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)

for i in range(5):
    print("Probabilidad de que colapse(n) ",i," banco(s): ",PH[i]/count)

sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)
sourceFile.close()

# ✅✅✅ NOW CALL THE FUNCTION (AFTER simulation completes) ✅✅✅
print(f"\nQ4 2008: Creating figures with {len(E)} scenarios...")
print(f"E range: ${min(E):,.0f} to ${max(E):,.0f}")
print(f"H range: ${min(H):,.0f} to ${max(H):,.0f}")

create_publication_figures(E, H, PH, count, 'Q4 2008', 'Q4 2008')

# Extract results
results_q4_2008 = extract_quarter_results(E, H, PH, count, "Q4 2008")
all_quarterly_results.append(results_q4_2008)

# Statistics
print(f"Q4 2008 - Mean E: ${np.mean(E):,.0f}M")
print(f"Q4 2008 - Mean H: ${np.mean(H):,.0f}M")
print(f"Q4 2008 - Mean SR: ${np.mean(np.array(E)+np.array(H)):,.0f}M")

sourceFile.close()

min(H)

max(H)

min(E)

max(E)

np.mean(E)

np.mean(H)

np.mean(H+E)

print(count)

A=ptime()
PMT=list(permutations([0, 1, 2,3]))
MC=[[126062,225409,780343],
    [145843,268040,969783],
    [161039,98747,874051],
    [46957,8093,353574]]
T1R=[0,0,0]
T2R=[0,0,0]
T3R=[0,0,0]
T4R=[0,0,0]
E=[]
H=[]
PH=[0,0,0,0,0]
s=442000 #Shock
count=0
for c in range(len(PMT)):
    T1C=MC[PMT[c][0]]
    T2C=MC[PMT[c][1]]
    T3C=MC[PMT[c][2]]
    T4C=MC[PMT[c][3]]
    for i in range(1,26):
        for j in range(1,26-i):
            for l in range(1,26):
                for n in range(1,26):
                    T1R=[0,0,0]
                    T2R=[0,0,0]
                    T3R=[0,0,0]
                    T4R=[0,0,0]
                    T1R=fill(T1R,T1C,s) #Shock inicial
                    k=100-i-j
                    T2R=fill(T2R,T2C,T1R[1]*(i/100)) #Primera interacción
                    T3R=fill(T3R,T3C,T1R[1]*(j/100))
                    T4R=fill(T4R,T4C,T1R[1]*(k/100))
                    T1R[1]=0
                    m=100-l
                    T3R=fill(T3R,T3C,T2R[1]*(l/100)) #Segunda interacción
                    T4R=fill(T4R,T4C,T2R[1]*(m/100))
                    T2R[1]=0
                    T4R=fill(T4R,T4C,T3R[1]*(n/100)) #Tercera interacción
                    T3R[1]-=T3R[1]*(n/100)
                    count+=1
                    E.append(T1R[0]+T2R[0]+T3R[0]+T4R[0])
                    H.append(T1R[2]+T2R[2]+T3R[2]+T4R[2])
                    PH[4-[T1R[1],T2R[1],T3R[1],T4R[1]].count(0)]+=1
                    #print(sum(T1R)+sum(T2R)+sum(T3R)+sum(T4R)) #Debe ser siempre igual al shock
sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)

for i in range(5):
    print("Probabilidad de que colapse(n) ",i," banco(s): ",PH[i]/count)

sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)
sourceFile.close()

# Create publication-quality figures
print(f"\nQ3 2008: Creating figures with {len(E)} scenarios...")
print(f"E range: ${min(E):,.0f} to ${max(E):,.0f}")
print(f"H range: ${min(H):,.0f} to ${max(H):,.0f}")

create_publication_figures(E, H, PH, count, 'Q3_2008', 'Q3 2008')

# Extract results
results_q3_2008 = extract_quarter_results(E, H, PH, count, "Q3 2008")
all_quarterly_results.append(results_q3_2008)

# Statistics
print(f"Q3 2008 - Mean E: ${np.mean(E):,.0f}M")
print(f"Q3 2008 - Mean H: ${np.mean(H):,.0f}M")
print(f"Q3 2008 - Mean SR: ${np.mean(np.array(E)+np.array(H)):,.0f}M")

np.mean(E)

np.mean(H)

max(E)

min(E)

max(H)

min(H)

np.mean(E+H)

print(count)

A=ptime()
PMT=list(permutations([0, 1, 2,3]))
MC=[[136405,220169,803642],
    [133176,193437,722905],
    [162691,114719,784764],
    [47964,4088,339124]]
T1R=[0,0,0]
T2R=[0,0,0]
T3R=[0,0,0]
T4R=[0,0,0]
E=[]
H=[]
PH=[0,0,0,0,0]
s=442000 #Shock
count=0
for c in range(len(PMT)):
    T1C=MC[PMT[c][0]]
    T2C=MC[PMT[c][1]]
    T3C=MC[PMT[c][2]]
    T4C=MC[PMT[c][3]]
    for i in range(1,26):
        for j in range(1,26-i):
            for l in range(1,26):
                for n in range(1,26):
                    T1R=[0,0,0]
                    T2R=[0,0,0]
                    T3R=[0,0,0]
                    T4R=[0,0,0]
                    T1R=fill(T1R,T1C,s) #Shock inicial
                    k=100-i-j
                    T2R=fill(T2R,T2C,T1R[1]*(i/100)) #Primera interacción
                    T3R=fill(T3R,T3C,T1R[1]*(j/100))
                    T4R=fill(T4R,T4C,T1R[1]*(k/100))
                    T1R[1]=0
                    m=100-l
                    T3R=fill(T3R,T3C,T2R[1]*(l/100)) #Segunda interacción
                    T4R=fill(T4R,T4C,T2R[1]*(m/100))
                    T2R[1]=0
                    T4R=fill(T4R,T4C,T3R[1]*(n/100)) #Tercera interacción
                    T3R[1]-=T3R[1]*(n/100)
                    count+=1
                    E.append(T1R[0]+T2R[0]+T3R[0]+T4R[0])
                    H.append(T1R[2]+T2R[2]+T3R[2]+T4R[2])
                    PH[4-[T1R[1],T2R[1],T3R[1],T4R[1]].count(0)]+=1
                    #print(sum(T1R)+sum(T2R)+sum(T3R)+sum(T4R)) #Debe ser siempre igual al shock
sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)

for i in range(5):
    print("Probabilidad de que colapse(n) ",i," banco(s): ",PH[i]/count)

sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)
sourceFile.close()

# Create publication-quality figures
print(f"\nQ2 2008: Creating figures with {len(E)} scenarios...")
print(f"E range: ${min(E):,.0f} to ${max(E):,.0f}")
print(f"H range: ${min(H):,.0f} to ${max(H):,.0f}")

create_publication_figures(E, H, PH, count, 'Q2_2008', 'Q2 2008')

# Extract results
results_q2_2008 = extract_quarter_results(E, H, PH, count, "Q2 2008")
all_quarterly_results.append(results_q2_2008)

# Statistics
print(f"Q2 2008 - Mean E: ${np.mean(E):,.0f}M")
print(f"Q2 2008 - Mean H: ${np.mean(H):,.0f}M")
print(f"Q2 2008 - Mean SR: ${np.mean(np.array(E)+np.array(H)):,.0f}M")

np.mean(E)

np.mean(H)

np.mean(E+H)

max(E)

min(E)

max(H)

min(H)

print(count)

A=ptime()
PMT=list(permutations([0, 1, 2,3]))
MC=[[128219,239006,831208],
    [125627,215590,761626],
    [156309,129096,797069],
    [48159,4171,358144]]
T1R=[0,0,0]
T2R=[0,0,0]
T3R=[0,0,0]
T4R=[0,0,0]
E=[]
H=[]
PH=[0,0,0,0,0]
s=442000 #Shock
count=0
for c in range(len(PMT)):
    T1C=MC[PMT[c][0]]
    T2C=MC[PMT[c][1]]
    T3C=MC[PMT[c][2]]
    T4C=MC[PMT[c][3]]
    for i in range(1,26):
        for j in range(1,26-i):
            for l in range(1,26):
                for n in range(1,26):
                    T1R=[0,0,0]
                    T2R=[0,0,0]
                    T3R=[0,0,0]
                    T4R=[0,0,0]
                    T1R=fill(T1R,T1C,s) #Shock inicial
                    k=100-i-j
                    T2R=fill(T2R,T2C,T1R[1]*(i/100)) #Primera interacción
                    T3R=fill(T3R,T3C,T1R[1]*(j/100))
                    T4R=fill(T4R,T4C,T1R[1]*(k/100))
                    T1R[1]=0
                    m=100-l
                    T3R=fill(T3R,T3C,T2R[1]*(l/100)) #Segunda interacción
                    T4R=fill(T4R,T4C,T2R[1]*(m/100))
                    T2R[1]=0
                    T4R=fill(T4R,T4C,T3R[1]*(n/100)) #Tercera interacción
                    T3R[1]-=T3R[1]*(n/100)
                    count+=1
                    E.append(T1R[0]+T2R[0]+T3R[0]+T4R[0])
                    H.append(T1R[2]+T2R[2]+T3R[2]+T4R[2])
                    PH[4-[T1R[1],T2R[1],T3R[1],T4R[1]].count(0)]+=1
                    #print(sum(T1R)+sum(T2R)+sum(T3R)+sum(T4R)) #Debe ser siempre igual al shock
sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)

for i in range(5):
    print("Probabilidad de que colapse(n) ",i," banco(s): ",PH[i]/count)

sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)
sourceFile.close()

# Create publication-quality figures
print(f"\nQ1 2008: Creating figures with {len(E)} scenarios...")
print(f"E range: ${min(E):,.0f} to ${max(E):,.0f}")
print(f"H range: ${min(H):,.0f} to ${max(H):,.0f}")

create_publication_figures(E, H, PH, count, 'Q1_2008', 'Q1 2008')

# Extract results
results_q1_2008 = extract_quarter_results(E, H, PH, count, "Q1 2008")
all_quarterly_results.append(results_q1_2008)

# Statistics
print(f"Q1 2008 - Mean E: ${np.mean(E):,.0f}M")
print(f"Q1 2008 - Mean H: ${np.mean(H):,.0f}M")
print(f"Q1 2008 - Mean SR: ${np.mean(np.array(E)+np.array(H)):,.0f}M")

np.mean(E)

np.mean(H)

np.mean(H+E)

max(E)

min(E)

max(H)

min(H)

print(count)

A=ptime()
PMT=list(permutations([0, 1, 2,3]))
MC=[[113447,274066,826230],
    [123221,182363,740728],
    [146803,141325,805177],
    [47628,2754,344460]]
T1R=[0,0,0]
T2R=[0,0,0]
T3R=[0,0,0]
T4R=[0,0,0]
E=[]
H=[]
PH=[0,0,0,0,0]
s=442000 #Shock
count=0
for c in range(len(PMT)):
    T1C=MC[PMT[c][0]]
    T2C=MC[PMT[c][1]]
    T3C=MC[PMT[c][2]]
    T4C=MC[PMT[c][3]]
    for i in range(1,26):
        for j in range(1,26-i):
            for l in range(1,26):
                for n in range(1,26):
                    T1R=[0,0,0]
                    T2R=[0,0,0]
                    T3R=[0,0,0]
                    T4R=[0,0,0]
                    T1R=fill(T1R,T1C,s) #Shock inicial
                    k=100-i-j
                    T2R=fill(T2R,T2C,T1R[1]*(i/100)) #Primera interacción
                    T3R=fill(T3R,T3C,T1R[1]*(j/100))
                    T4R=fill(T4R,T4C,T1R[1]*(k/100))
                    T1R[1]=0
                    m=100-l
                    T3R=fill(T3R,T3C,T2R[1]*(l/100)) #Segunda interacción
                    T4R=fill(T4R,T4C,T2R[1]*(m/100))
                    T2R[1]=0
                    T4R=fill(T4R,T4C,T3R[1]*(n/100)) #Tercera interacción
                    T3R[1]-=T3R[1]*(n/100)
                    count+=1
                    E.append(T1R[0]+T2R[0]+T3R[0]+T4R[0])
                    H.append(T1R[2]+T2R[2]+T3R[2]+T4R[2])
                    PH[4-[T1R[1],T2R[1],T3R[1],T4R[1]].count(0)]+=1
                    #print(sum(T1R)+sum(T2R)+sum(T3R)+sum(T4R)) #Debe ser siempre igual al shock
sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)

for i in range(5):
    print("Probabilidad de que colapse(n) ",i," banco(s): ",PH[i]/count)

sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)
sourceFile.close()

# Create publication-quality figures
print(f"\nQ4 2007: Creating figures with {len(E)} scenarios...")
print(f"E range: ${min(E):,.0f} to ${max(E):,.0f}")
print(f"H range: ${min(H):,.0f} to ${max(H):,.0f}")

create_publication_figures(E, H, PH, count, 'Q4_2007', 'Q4 2007')

# Extract results
results_q4_2007 = extract_quarter_results(E, H, PH, count, "Q4 2007")
all_quarterly_results.append(results_q4_2007)

# Statistics
print(f"Q4 2007 - Mean E: ${np.mean(E):,.0f}M")
print(f"Q4 2007 - Mean H: ${np.mean(H):,.0f}M")
print(f"Q4 2007 - Mean SR: ${np.mean(np.array(E)+np.array(H)):,.0f}M")

np.mean(E)

np.mean(H)

np.mean(H+E)

max(E)

min(E)

max(H)

min(H)

print(count)

A=ptime()
PMT=list(permutations([0, 1, 2,3]))
MC=[[127113,228556.6,812850],
    [119978,162303,678091],
    [138510,143979,699222],
    [47738,4546,334956]]
T1R=[0,0,0]
T2R=[0,0,0]
T3R=[0,0,0]
T4R=[0,0,0]
E=[]
H=[]
PH=[0,0,0,0,0]
s=442000 #Shock
count=0
for c in range(len(PMT)):
    T1C=MC[PMT[c][0]]
    T2C=MC[PMT[c][1]]
    T3C=MC[PMT[c][2]]
    T4C=MC[PMT[c][3]]
    for i in range(1,26):
        for j in range(1,26-i):
            for l in range(1,26):
                for n in range(1,26):
                    T1R=[0,0,0]
                    T2R=[0,0,0]
                    T3R=[0,0,0]
                    T4R=[0,0,0]
                    T1R=fill(T1R,T1C,s) #Shock inicial
                    k=100-i-j
                    T2R=fill(T2R,T2C,T1R[1]*(i/100)) #Primera interacción
                    T3R=fill(T3R,T3C,T1R[1]*(j/100))
                    T4R=fill(T4R,T4C,T1R[1]*(k/100))
                    T1R[1]=0
                    m=100-l
                    T3R=fill(T3R,T3C,T2R[1]*(l/100)) #Segunda interacción
                    T4R=fill(T4R,T4C,T2R[1]*(m/100))
                    T2R[1]=0
                    T4R=fill(T4R,T4C,T3R[1]*(n/100)) #Tercera interacción
                    T3R[1]-=T3R[1]*(n/100)
                    count+=1
                    E.append(T1R[0]+T2R[0]+T3R[0]+T4R[0])
                    H.append(T1R[2]+T2R[2]+T3R[2]+T4R[2])
                    PH[4-[T1R[1],T2R[1],T3R[1],T4R[1]].count(0)]+=1
                    #print(sum(T1R)+sum(T2R)+sum(T3R)+sum(T4R)) #Debe ser siempre igual al shock
sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)

for i in range(5):
    print("Probabilidad de que colapse(n) ",i," banco(s): ",PH[i]/count)

sourceFile = open('res_samuel.txt', 'w')
print('Cantidad de escenarios: ',count,file = sourceFile)
print('Tiempo de ejecución: ',ptime()-A,' s',file = sourceFile)
sourceFile.close()

# Create publication-quality figures
print(f"\nQ3 2007: Creating figures with {len(E)} scenarios...")
print(f"E range: ${min(E):,.0f} to ${max(E):,.0f}")
print(f"H range: ${min(H):,.0f} to ${max(H):,.0f}")

create_publication_figures(E, H, PH, count, 'Q3_2007', 'Q3 2007')

# Extract results
results_q3_2007 = extract_quarter_results(E, H, PH, count, "Q3 2007")
all_quarterly_results.append(results_q3_2007)

# Statistics
print(f"Q3 2007 - Mean E: ${np.mean(E):,.0f}M")
print(f"Q3 2007 - Mean H: ${np.mean(H):,.0f}M")
print(f"Q3 2007 - Mean SR: ${np.mean(np.array(E)+np.array(H)):,.0f}M")

np.mean(E)

np.mean(H)

np.mean(E+H)

max(E)

min(E)

max(H)

min(H)

print(count)

# Reverse to chronological order
all_quarterly_results.reverse()

# @title SUMMARY STATISTICS FOR ALL QUARTERS
# ============================================================================

print("\n" + "="*80)
print("SUMMARY: KEY METRICS BY QUARTER")
print("="*80)
for r in all_quarterly_results:
    print(f"\n{r['Quarter']}:")
    print(f"  Mean Systemic Risk: ${r['Mean_SR']:,.0f}M")
    print(f"  Mean Equity Loss: ${r['Mean_E']:,.0f}M")
    print(f"  Mean External Debt Loss: ${r['Mean_H']:,.0f}M")
    print(f"  P(≥1 bank fails): {r['P_at_least_1']*100:.2f}%")
    print(f"  Expected # failures: {r['Expected_failures']:.3f}")

# ============================================================================
# TABLE 2: SUMMARY STATISTICS (Markdown Format)
# ============================================================================

print("\n" + "="*80)
print("TABLE 2: SUMMARY STATISTICS (Copy to Paper)")
print("="*80)
print("\n| Quarter  | Mean E      | Min E       | Max E       | Mean H      | Min H       | Max H       | Mean SR     |")
print("|----------|-------------|-------------|-------------|-------------|-------------|-------------|-------------|")
for r in all_quarterly_results:
    print(f"| {r['Quarter']:8s} | ${r['Mean_E']:11,.0f} | ${r['Min_E']:11,.0f} | ${r['Max_E']:11,.0f} | "
          f"${r['Mean_H']:11,.0f} | ${r['Min_H']:11,.0f} | ${r['Max_H']:11,.0f} | ${r['Mean_SR']:11,.0f} |")

# ============================================================================
# TABLE 3: FAILURE PROBABILITIES (Markdown Format)
# ============================================================================

print("\n" + "="*80)
print("TABLE 3: FAILURE PROBABILITIES (Copy to Paper)")
print("="*80)
print("\n| Quarter  | P(0 banks) | P(1 bank) | P(2 banks) | P(3 banks) | P(4 banks) | P(≥1 bank) |")
print("|----------|------------|-----------|------------|------------|------------|------------|")
for r in all_quarterly_results:
    print(f"| {r['Quarter']:8s} | {r['P_0_banks']*100:9.2f}% | {r['P_1_bank']*100:8.2f}% | "
          f"{r['P_2_banks']*100:9.2f}% | {r['P_3_banks']*100:9.2f}% | {r['P_4_banks']*100:9.2f}% | "
          f"{r['P_at_least_1']*100:9.2f}% |")

# ============================================================================
# KEY FINDINGS FOR PAPER
# ============================================================================

print("\n" + "="*80)
print("KEY FINDINGS FOR PAPER (Copy to Results Section)")
print("="*80)

baseline = all_quarterly_results[0]['Mean_SR']
peak_quarter = max(all_quarterly_results, key=lambda x: x['Mean_SR'])
avg_p_failure = np.mean([r['P_at_least_1'] for r in all_quarterly_results])

print(f"\n1. TEMPORAL EVOLUTION:")
print(f"   - Baseline (Q3 2007): ${baseline:,.0f}M")
print(f"   - Peak quarter: {peak_quarter['Quarter']} at ${peak_quarter['Mean_SR']:,.0f}M")
print(f"   - Total increase: {((peak_quarter['Mean_SR'] - baseline) / baseline * 100):.1f}%")

print(f"\n2. CRITICAL PERCOLATION FINDING:")
print(f"   - Average P(≥1 bank fails) across all quarters = {avg_p_failure*100:.2f}%")
print(f"   - Theoretical critical threshold p_c ≈ 59.27%")
if 55 < avg_p_failure*100 < 65:
    print(f"   - INTERPRETATION: ALIGNS with critical percolation theory")
elif avg_p_failure*100 < 55:
    print(f"   - INTERPRETATION: BELOW critical threshold (subcritical regime)")
else:
    print(f"   - INTERPRETATION: ABOVE critical threshold (supercritical regime)")

print(f"\n3. MULTI-BANK COLLAPSE RISK:")
max_p_2 = max([r['P_at_least_2'] for r in all_quarterly_results])
print(f"   - Maximum P(≥2 banks fail) = {max_p_2*100:.2f}%")
if max_p_2 < 0.05:
    print(f"   - INTERPRETATION: Multiple simultaneous collapses are RARE")
else:
    print(f"   - INTERPRETATION: Significant risk of cascade failures")

print(f"\n4. QUARTERLY BREAKDOWN:")
for r in all_quarterly_results:
    pct_from_baseline = ((r['Mean_SR'] - baseline) / baseline * 100)
    print(f"   {r['Quarter']}: ${r['Mean_SR']:>10,.0f}M ({pct_from_baseline:+6.1f}% from baseline), "
          f"P(≥1)={r['P_at_least_1']*100:5.2f}%")

# ============================================================================
# EXPORT TO CSV
# ============================================================================

df = pd.DataFrame(all_quarterly_results)
df.to_csv('flow_network_results.csv', index=False)
print("\n" + "="*80)
print("✓ Results exported to: flow_network_results.csv")
print("="*80)

# ============================================================================
# FIGURE: TEMPORAL EVOLUTION OF SYSTEMIC RISK
# ============================================================================

print("\n" + "="*80)
print("Creating temporal evolution and comparison figures...")
print("="*80)

quarters = [r['Quarter'] for r in all_quarterly_results]
mean_SR = [r['Mean_SR']/1000 for r in all_quarterly_results]

fig, ax = plt.subplots(figsize=(10, 6), dpi=600)
ax.plot(quarters, mean_SR, marker='o', linewidth=2.5, markersize=10,
        color='#2E86AB', markerfacecolor='#2E86AB',
        markeredgecolor='white', markeredgewidth=1.5,
        label='Mean Systemic Risk')

for i, (q, sr) in enumerate(zip(quarters, mean_SR)):
    ax.annotate(f'${sr:.1f}B',
               xy=(i, sr),
               xytext=(0, 12),
               textcoords='offset points',
               ha='center',
               fontsize=9,
               fontweight='bold',
               bbox=dict(boxstyle='round,pad=0.4', facecolor='yellow', alpha=0.7, edgecolor='black'))

ax.set_xlabel('Quarter', fontweight='bold', fontsize=12)
ax.set_ylabel('Mean Systemic Risk (Billions USD)', fontweight='bold', fontsize=12)
ax.set_title('Temporal Evolution of Systemic Risk\n(Flow Network Model, Q3 2007 - Q4 2008)',
            fontweight='bold', fontsize=13, pad=20)

# Crisis period: Q3 2008 onwards (indices 4-5 in 0-indexed array)
ax.axvspan(3.5, 5.5, alpha=0.15, color='red', label='Peak Crisis Period (Post-Lehman)')

ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)
ax.set_axisbelow(True)
ax.legend(loc='best', frameon=True, shadow=True)

plt.xticks(rotation=45, ha='right')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig('Fig_Temporal_Evolution_Systemic_Risk.png', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('Fig_Temporal_Evolution_Systemic_Risk.tiff', dpi=600, bbox_inches='tight', facecolor='white')
plt.show()
print("✓ Created Fig_Temporal_Evolution_Systemic_Risk.png")

# ============================================================================
# FIGURE: FAILURE PROBABILITY EVOLUTION (STACKED BAR)
# ============================================================================

fig, ax = plt.subplots(figsize=(10, 6), dpi=600)

quarters_labels = [r['Quarter'] for r in all_quarterly_results]
x_pos = np.arange(len(quarters_labels))

p_0 = [r['P_0_banks'] for r in all_quarterly_results]
p_1 = [r['P_1_bank'] for r in all_quarterly_results]
p_2 = [r['P_2_banks'] for r in all_quarterly_results]
p_3 = [r['P_3_banks'] for r in all_quarterly_results]
p_4 = [r['P_4_banks'] for r in all_quarterly_results]

ax.bar(x_pos, p_0, label='0 banks', color='#2ecc71', alpha=0.9, edgecolor='black', linewidth=1)
ax.bar(x_pos, p_1, bottom=p_0, label='1 bank', color='#3498db', alpha=0.9, edgecolor='black', linewidth=1)
ax.bar(x_pos, p_2, bottom=np.array(p_0)+np.array(p_1), label='2 banks',
       color='#f39c12', alpha=0.9, edgecolor='black', linewidth=1)
ax.bar(x_pos, p_3, bottom=np.array(p_0)+np.array(p_1)+np.array(p_2),
       label='3 banks', color='#e74c3c', alpha=0.9, edgecolor='black', linewidth=1)
ax.bar(x_pos, p_4, bottom=np.array(p_0)+np.array(p_1)+np.array(p_2)+np.array(p_3),
       label='4 banks', color='#8e44ad', alpha=0.9, edgecolor='black', linewidth=1)

ax.set_xlabel('Quarter', fontsize=12, fontweight='bold')
ax.set_ylabel('Probability', fontsize=12, fontweight='bold')
ax.set_title('Bank Failure Probability Evolution (Q3 2007 - Q4 2008)',
             fontsize=14, fontweight='bold', pad=15)
ax.set_xticks(x_pos)
ax.set_xticklabels(quarters_labels, rotation=45, ha='right')
ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y*100:.0f}%'))
ax.legend(title='Banks Failed', loc='upper right', frameon=True, shadow=True)
ax.grid(True, alpha=0.3, linestyle='--', linewidth=0.5, axis='y')
ax.set_axisbelow(True)

plt.tight_layout()
plt.savefig('Fig_Failure_Evolution_All_Quarters.png', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('Fig_Failure_Evolution_All_Quarters.tiff', dpi=600, bbox_inches='tight', facecolor='white')
plt.show()
print("✓ Created Fig_Failure_Evolution_All_Quarters.png")

# ============================================================================
# FIGURE: SYSTEMIC RISK COMPONENTS (E vs H) EVOLUTION
# ============================================================================

fig, ax = plt.subplots(figsize=(10, 6), dpi=600)

quarters_labels = [r['Quarter'] for r in all_quarterly_results]
x_pos = np.arange(len(quarters_labels))

mean_E = [r['Mean_E']/1000 for r in all_quarterly_results]
mean_H = [r['Mean_H']/1000 for r in all_quarterly_results]

ax.fill_between(x_pos, 0, mean_E, label='Equity Losses (E)',
                color='steelblue', alpha=0.7, edgecolor='black', linewidth=1.5)
ax.fill_between(x_pos, mean_E, np.array(mean_E)+np.array(mean_H),
                label='External Debt Losses (H)',
                color='coral', alpha=0.7, edgecolor='black', linewidth=1.5)

total_SR = [r['Mean_SR']/1000 for r in all_quarterly_results]
ax.plot(x_pos, total_SR, color='darkred', linewidth=3, marker='o',
        markersize=8, label='Total Systemic Risk', zorder=10)

ax.set_xlabel('Quarter', fontsize=12, fontweight='bold')
ax.set_ylabel('Mean Loss (Billions USD)', fontsize=12, fontweight='bold')
ax.set_title('Systemic Risk Components Evolution (Q3 2007 - Q4 2008)\n(Equity vs. External Debt)',
             fontsize=14, fontweight='bold', pad=15)
ax.set_xticks(x_pos)
ax.set_xticklabels(quarters_labels, rotation=45, ha='right')
ax.legend(loc='upper left', bbox_to_anchor=(0.01, 0.88), frameon=True, shadow=True, fontsize=10)
ax.grid(True, alpha=0.3, linestyle='--', axis='y')
ax.set_axisbelow(True)

for i, (xp, sr) in enumerate(zip(x_pos, total_SR)):
    ax.annotate(f'${sr:.0f}B', xy=(xp, sr), xytext=(0, 10),
               textcoords='offset points', ha='center', fontsize=9,
               bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))

plt.tight_layout()
plt.savefig('Fig_SR_Components_Evolution.png', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('Fig_SR_Components_Evolution.tiff', dpi=600, bbox_inches='tight', facecolor='white')
plt.show()
print("✓ Created Fig_SR_Components_Evolution.png")

# ============================================================================
# FIGURE: FAILURE METRICS vs PERCOLATION THRESHOLD
# ============================================================================

fig, ax = plt.subplots(figsize=(10, 6), dpi=600)

expected_failures = [r['Expected_failures'] for r in all_quarterly_results]
p_at_least_1 = [r['P_at_least_1']*100 for r in all_quarterly_results]

ax1 = ax
ax2 = ax1.twinx()

line1 = ax1.plot(x_pos, expected_failures, color='#e74c3c', linewidth=3,
                 marker='s', markersize=10, label='Expected # Failures', zorder=5)
ax1.set_ylabel('Expected Number of Bank Failures', fontsize=12, fontweight='bold', color='#e74c3c')
ax1.tick_params(axis='y', labelcolor='#e74c3c')
ax1.set_ylim(0, max(expected_failures) * 1.2)

line2 = ax2.plot(x_pos, p_at_least_1, color='#3498db', linewidth=3,
                 marker='o', markersize=10, label='P(≥1 failure)', zorder=5)
ax2.set_ylabel('Probability of At Least One Failure (%)', fontsize=12, fontweight='bold', color='#3498db')
ax2.tick_params(axis='y', labelcolor='#3498db')
ax2.set_ylim(0, 100)

ax2.axhline(y=59.27, color='green', linestyle='--', linewidth=2,
            label='Critical Percolation (59.27%)', alpha=0.7)

ax1.set_xlabel('Quarter', fontsize=12, fontweight='bold')
ax1.set_title('Bank Failure Metrics Evolution (Q3 2007 - Q4 2008)\nvs. Critical Percolation Threshold',
              fontsize=14, fontweight='bold', pad=15)
ax1.set_xticks(x_pos)
ax1.set_xticklabels(quarters_labels, rotation=45, ha='right')
ax1.grid(True, alpha=0.3, linestyle='--', axis='both')
ax1.set_axisbelow(True)

lines = line1 + line2 + [plt.Line2D([0], [0], color='green', linestyle='--', linewidth=2)]
labels = ['Expected # Failures', 'P(≥1 failure)', 'Critical Percolation (59.27%)']
ax1.legend(lines, labels, loc='upper left', frameon=True, shadow=True)

plt.tight_layout()
plt.savefig('Fig_Failure_Metrics_vs_Percolation.png', dpi=600, bbox_inches='tight', facecolor='white')
plt.savefig('Fig_Failure_Metrics_vs_Percolation.tiff', dpi=600, bbox_inches='tight', facecolor='white')
plt.show()
print("✓ Created Fig_Failure_Metrics_vs_Percolation.png")

# ============================================================================
# FINAL SUMMARY
# ============================================================================

print("\n" + "="*80)
print("✓✓✓ ALL RESULTS PROCESSING COMPLETE! ✓✓✓")
print("="*80)
print(f"\nGenerated Files:")
print(f"  - 24 individual quarter figures (4 per quarter × 6 quarters)")
print(f"  - 4 comparison/evolution figures")
print(f"  - 1 CSV file: flow_network_results.csv")
print(f"\nTotal: 29 output files")
print(f"\nNext steps:")
print(f"  1. Review figures in Colab files panel")
print(f"  2. Download figures for paper")
print(f"  3. Copy tables to paper Results section")
print(f"  4. Use key findings in Discussion section")
print("="*80)

# Check current state
print(f"Total entries in all_quarterly_results: {len(all_quarterly_results)}")
print(f"Expected: 6")
print(f"Actual unique quarters: {len(set(r['Quarter'] for r in all_quarterly_results))}")

print("\nAll entries:")
for i, result in enumerate(all_quarterly_results, 1):
    print(f"  {i}. {result['Quarter']}")

"""
Figure Generation: Flow Network vs SRISK Comparison
For MDPI Complexities Journal - Financial Network Engineering Paper
Section 5.8: External Validation
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

# Set publication-quality parameters
plt.rcParams['figure.dpi'] = 600
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.size'] = 11
plt.rcParams['axes.linewidth'] = 1.5
plt.rcParams['legend.framealpha'] = 1.0

# ============================================================================
# DATA: Flow Network SR and SRISK Estimates
# ============================================================================

quarters = ['Q3 2007', 'Q4 2007', 'Q1 2008', 'Q2 2008', 'Q3 2008', 'Q4 2008']
x_pos = np.arange(len(quarters))

# Flow Network Model: Mean Systemic Risk (E + H) in billions USD
flow_network_sr = np.array([429.7, 421.8, 425.5, 433.0, 421.4, 422.6])

# SRISK (4 banks): Aggregated from institution-level V-Lab data
# Values represent end-of-month SRISK for Sep-07, Dec-07, Mar-08, Jun-08, Sep-08, Dec-08
# Note: Negative institution-level SRISK (capital surplus) included in aggregation
srisk_4banks = np.array([19.6, 128.7, 184.2, 252.9, 241.2, 393.1])

# Calculate ratio (Flow Network / SRISK)
ratio = flow_network_sr / srisk_4banks

# ============================================================================
# FIGURE: DUAL-PANEL COMPARISON
# ============================================================================

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8), dpi=600,
                                gridspec_kw={'height_ratios': [2, 1]})

# ---------------------------------------------------------------------------
# PANEL 1: Absolute Values (Flow Network SR vs SRISK)
# ---------------------------------------------------------------------------

# Plot Flow Network SR
line1 = ax1.plot(x_pos, flow_network_sr, marker='o', markersize=8,
                  linewidth=2.5, color='steelblue', label='Flow Network SR',
                  markeredgecolor='black', markeredgewidth=1)

# Plot SRISK
line2 = ax1.plot(x_pos, srisk_4banks, marker='s', markersize=8,
                  linewidth=2.5, color='coral', label='SRISK (4 banks)',
                  markeredgecolor='black', markeredgewidth=1)

# Shade convergence region (Flow Network always > SRISK)
ax1.fill_between(x_pos, flow_network_sr, srisk_4banks,
                  alpha=0.2, color='steelblue',
                  label='Flow Network > SRISK')

# Add value labels for key points
# Q3 2007 (maximum divergence)
ax1.annotate(f'${flow_network_sr[0]:.1f}B',
             xy=(0, flow_network_sr[0]),
             xytext=(0, 10), textcoords='offset points',
             ha='center', fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='steelblue',
                      alpha=0.7, edgecolor='black'))
ax1.annotate(f'${srisk_4banks[0]:.1f}B',
             xy=(0, srisk_4banks[0]),
             xytext=(0, -15), textcoords='offset points',
             ha='center', fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='coral',
                      alpha=0.7, edgecolor='black'))

# Q4 2008 (near convergence)
ax1.annotate(f'${flow_network_sr[5]:.1f}B',
             xy=(5, flow_network_sr[5]),
             xytext=(0, 10), textcoords='offset points',
             ha='center', fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='steelblue',
                      alpha=0.7, edgecolor='black'))
ax1.annotate(f'${srisk_4banks[5]:.1f}B',
             xy=(5, srisk_4banks[5]),
             xytext=(0, -15), textcoords='offset points',
             ha='center', fontsize=9, fontweight='bold',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='coral',
                      alpha=0.7, edgecolor='black'))

# Formatting Panel 1
ax1.set_ylabel('Systemic Risk (Billions USD)', fontsize=12, fontweight='bold')
ax1.set_title('Flow Network Model vs. SRISK: Systemic Risk Evolution (2007-2008)',
              fontsize=14, fontweight='bold', pad=15)
ax1.set_xticks(x_pos)
ax1.set_xticklabels(quarters, rotation=45, ha='right')
ax1.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)
ax1.set_axisbelow(True)
ax1.legend(loc='upper left', frameon=True, shadow=True, fontsize=10)
ax1.set_ylim([0, 500])

# Add shaded crisis period
ax1.axvspan(3.5, 5.5, alpha=0.1, color='red', zorder=0)
ax1.text(4.1, 480, 'Peak Crisis Period\n(Post-Lehman)',
         ha='center', va='top', fontsize=9, style='italic',
         bbox=dict(boxstyle='round,pad=0.5', facecolor='white',
                  alpha=0.8, edgecolor='red'))

# ---------------------------------------------------------------------------
# PANEL 2: Ratio (Flow Network / SRISK)
# ---------------------------------------------------------------------------

# Plot ratio evolution
ax2.plot(x_pos, ratio, marker='D', markersize=7, linewidth=2.5,
         color='darkgreen', markeredgecolor='black', markeredgewidth=1,
         label='Flow Network / SRISK Ratio')

# Add reference line at ratio = 1.0 (perfect agreement)
ax2.axhline(y=1.0, color='black', linestyle='--', linewidth=1.5,
            label='Parity (Ratio = 1.0)', alpha=0.7)

# Shade region (Flow Network always > SRISK, ratio always > 1)
ax2.fill_between(x_pos, 1.0, ratio,
                  alpha=0.2, color='steelblue', interpolate=True,
                  label='Flow Network > SRISK')

# Add annotations for key points
ax2.annotate(f'Ratio = {ratio[0]:.1f}×\n(Max Divergence)',
             xy=(0, ratio[0]), xytext=(1.2, 18),
             arrowprops=dict(arrowstyle='->', lw=1.5, color='steelblue'),
             fontsize=9, ha='center', fontweight='bold')

ax2.annotate(f'Ratio = {ratio[5]:.2f}×\n(Near Parity)',
             xy=(5, ratio[5]), xytext=(4.0, 5),
             arrowprops=dict(arrowstyle='->', lw=1.5, color='darkgreen'),
             fontsize=9, ha='center', fontweight='bold')

# Formatting Panel 2
ax2.set_xlabel('Quarter', fontsize=12, fontweight='bold')
ax2.set_ylabel('Ratio', fontsize=12, fontweight='bold')
ax2.set_title('Convergence Pattern: Flow Network Captures Latent Vulnerabilities → Market Pricing Converges at Peak Crisis',
              fontsize=11, fontweight='bold', pad=10)
ax2.set_xticks(x_pos)
ax2.set_xticklabels(quarters, rotation=45, ha='right')
ax2.grid(True, alpha=0.3, linestyle='--', linewidth=0.5)
ax2.set_axisbelow(True)
ax2.legend(loc='upper right', frameon=True, shadow=True, fontsize=9)
ax2.set_ylim([0, 25])

# Add shaded crisis period
ax2.axvspan(3.5, 5.5, alpha=0.1, color='red', zorder=0)

plt.tight_layout()

# Save figure
plt.savefig('Fig_Flow_Network_vs_SRISK_Comparison.png', dpi=600,
            bbox_inches='tight', facecolor='white')
plt.savefig('Fig_Flow_Network_vs_SRISK_Comparison.tiff', dpi=600,
            bbox_inches='tight', facecolor='white')
plt.show()

print("\n" + "="*80)
print("✓ Created Fig_Flow_Network_vs_SRISK_Comparison.png")
print("✓ Created Fig_Flow_Network_vs_SRISK_Comparison.tiff")
print("="*80)

# ============================================================================
# NUMERICAL SUMMARY TABLE (for manuscript)
# ============================================================================

print("\n" + "="*80)
print("TABLE: Flow Network vs SRISK Comparison")
print("="*80)
print("\n| Quarter  | Flow Net SR | SRISK (4 banks) | Ratio  | Δ Abs.   | Δ %      |")
print("|----------|-------------|-----------------|--------|----------|----------|")
for i, q in enumerate(quarters):
    delta_abs = flow_network_sr[i] - srisk_4banks[i]
    delta_pct = ((flow_network_sr[i] / srisk_4banks[i]) - 1) * 100
    print(f"| {q:8s} | ${flow_network_sr[i]:5.1f}B      | ${srisk_4banks[i]:5.1f}B          | "
          f"{ratio[i]:6.2f} | {delta_abs:+7.1f}B | {delta_pct:+7.1f}% |")

print("\n" + "="*80)
print("KEY FINDINGS:")
print("="*80)
print(f"1. Maximum divergence (Q3 2007): Flow Network = ${flow_network_sr[0]:.1f}B, "
      f"SRISK = ${srisk_4banks[0]:.1f}B → Ratio = {ratio[0]:.1f}×")
print(f"2. Progressive convergence: Ratio declines from {ratio[0]:.1f}× to {ratio[5]:.2f}×")
print(f"3. Near parity (Q4 2008): Flow Network = ${flow_network_sr[5]:.1f}B, "
      f"SRISK = ${srisk_4banks[5]:.1f}B → Ratio = {ratio[5]:.2f}×")
print(f"4. Gap narrowing: From ${abs(flow_network_sr[0] - srisk_4banks[0]):.1f}B (Q3 2007) "
      f"to ${abs(flow_network_sr[5] - srisk_4banks[5]):.1f}B (Q4 2008)")
print("="*80)

# ============================================================================
# INTERPRETATION SUMMARY
# ============================================================================

print("\n" + "="*80)
print("INTERPRETATION FOR MANUSCRIPT:")
print("="*80)
print("""
The convergence pattern validates the complementarity of deterministic
and stochastic approaches:

1. MAXIMUM DIVERGENCE (Q3 2007):
   - Flow Network exceeds SRISK by factor of 21.9×
   - SRISK = $19.6B (Bank of America and Wells Fargo negative)
   - Structural model captures latent vulnerabilities before market repricing

2. PROGRESSIVE CONVERGENCE (Q4 2007 - Q3 2008):
   - Ratio declines: 21.9× → 3.3× → 2.3× → 1.7× → 1.8×
   - Market-implied SRISK gradually incorporates balance-sheet fragilities
   - Non-monotonic SRISK in Q3 2008 due to Wells Fargo's negative contribution

3. NEAR PARITY (Q4 2008):
   - Ratio = 1.08× (Flow Network only 8% above SRISK)
   - All four institutions exhibit positive SRISK for first time
   - Market pricing converges to structural fundamentals at peak crisis

POLICY IMPLICATIONS:
- Flow Network provides early warning of structural vulnerabilities
- Large divergence (ratio >> 1) signals underpriced systemic risk
- Near convergence indicates market has incorporated balance-sheet risks
- Use BOTH measures: Flow Network for stress testing, SRISK for real-time surveillance
""")
print("="*80)

# @title Utility function required by sensitivity analysis

def fill(R, C, Q):
    """
    Apply the three-stage loss waterfall from your paper:
      R : residual vector [Equity_loss, Interbank_residual, ExtDebt_loss]
      C : capacity vector  [Equity_cap, Interbank_cap, ExtDebt_cap]
      Q : incoming shock
    """
    e_cap, d_cap, h_cap = C  # capacities for equity, interbank, external debt
    e_res, d_res, h_res = R  # residual losses

    # Step 1 — Equity absorbs first
    a = min(Q, e_cap - e_res)
    e_res += a
    Q -= a

    # Step 2 — Interbank absorbs next (produces contagion loss)
    b = min(Q, d_cap - d_res)
    d_res += b
    Q -= b

    # Step 3 — External debt absorbs the rest
    c = min(Q, h_cap - h_res)
    h_res += c
    Q -= c

    # Update the residual vector
    return [e_res, d_res, h_res]

# @title Setup

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from itertools import permutations

# @title SENSITIVITY ANALYSIS — Shock Magnitude & Diversification Cap (Q4 2008, with progress bar)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from itertools import permutations
from tqdm.auto import tqdm

# ---------------------------------------------------------------------------
# Waterfall function (matches your MDPI implementation exactly)
# ---------------------------------------------------------------------------

def fill(AR, AC, qt):
    """
    Loss waterfall used in the Flow Network model:
      1) Equity absorbs first, up to its capacity
      2) Interbank absorbs next, up to its capacity
      3) Any residual goes to external debt

    AR: residual vector [Equity_loss, Interbank_residual, ExtDebt_loss]
    AC: capacity vector  [Equity_cap,   Interbank_cap,   ExtDebt_cap]
    qt: incoming shock
    """
    if qt + AR[0] > AC[0]:
        qt2 = qt + AR[0] - AC[0]
        AR[0] = AC[0]
        if qt2 + AR[1] > AC[1]:
            qt3 = qt2 + AR[1] - AC[1]
            AR[1] = AC[1]
            AR[2] += qt3
        else:
            AR[1] += qt2
    else:
        AR[0] += qt
    return AR


# ---------------------------------------------------------------------------
# Sensitivity runner for a single quarter
# ---------------------------------------------------------------------------

def run_flow_network_quarter_sensitivity(
    MC,
    shock,
    max_share_pct=0.25,
    quarter_name="Q4 2008",
    show_progress=True
):
    """
    Run the Flow Network Model for a single quarter with:
      - MC: 4x3 balance-sheet matrix (millions USD)
      - shock: scalar shock (millions USD)
      - max_share_pct: single-counterparty cap (e.g., 0.25 for 25%)
      - show_progress: if True, show tqdm progress bar

    Returns a dict with:
      Mean_SR, P_at_least_1, P_at_least_2, Expected_failures, VaR95_SR, CVaR95_SR, ...
    """

    max_share = int(round(max_share_pct * 100))   # e.g., 0.25 -> 25

    PMT = list(permutations([0, 1, 2, 3]))

    E = []
    H = []
    PH = [0, 0, 0, 0, 0]  # counts of 0,1,2,3,4 failures
    count = 0

    # --------- Precompute total number of scenarios for the progress bar ---------
    base_per_l_n = max_share * max_share
    pair_count = sum((max_share + 1 - i) for i in range(1, max_share + 1))
    total_scenarios = len(PMT) * pair_count * base_per_l_n

    pbar = tqdm(
        total=total_scenarios,
        disable=not show_progress,
        desc=f"{quarter_name} | shock={shock:,.0f}M, cap={int(max_share_pct*100)}%"
    )

    # -----------------------------------------------------------------------
    # MAIN ENUMERATION (identical logic to your simulation, with progress)
    # -----------------------------------------------------------------------
    for c in range(len(PMT)):
        T1C = MC[PMT[c][0]]
        T2C = MC[PMT[c][1]]
        T3C = MC[PMT[c][2]]
        T4C = MC[PMT[c][3]]

        for i in range(1, max_share + 1):
            for j in range(1, max_share + 1 - i):

                # We'll update the progress bar once per (i,j) pair
                # after looping over all (l,n)
                scenarios_this_ij = 0

                for l in range(1, max_share + 1):
                    for n in range(1, max_share + 1):
                        # Residual vectors: [E_loss, IB_residual, H_loss]
                        T1R = [0, 0, 0]
                        T2R = [0, 0, 0]
                        T3R = [0, 0, 0]
                        T4R = [0, 0, 0]

                        # Initial shock into T1
                        T1R = fill(T1R, T1C, shock)

                        # First interaction: distribute T1R[1] (interbank residual) to T2, T3, T4
                        k = 100 - i - j
                        T2R = fill(T2R, T2C, T1R[1] * (i / 100.0))
                        T3R = fill(T3R, T3C, T1R[1] * (j / 100.0))
                        T4R = fill(T4R, T4C, T1R[1] * (k / 100.0))
                        T1R[1] = 0

                        # Second interaction: distribute T2R[1] to T3 and T4
                        m = 100 - l
                        T3R = fill(T3R, T3C, T2R[1] * (l / 100.0))
                        T4R = fill(T4R, T4C, T2R[1] * (m / 100.0))
                        T2R[1] = 0

                        # Third interaction: distribute T3R[1] to T4 / kept at T3
                        T4R = fill(T4R, T4C, T3R[1] * (n / 100.0))
                        T3R[1] -= T3R[1] * (n / 100.0)

                        count += 1
                        scenarios_this_ij += 1

                        # Aggregate equity and external-debt losses
                        E.append(T1R[0] + T2R[0] + T3R[0] + T4R[0])
                        H.append(T1R[2] + T2R[2] + T3R[2] + T4R[2])

                        # Failures: number of banks with non-zero interbank residual
                        alive_flags = [T1R[1], T2R[1], T3R[1], T4R[1]]
                        n_fail = 4 - alive_flags.count(0)
                        PH[n_fail] += 1

                # Update progress bar once for all (l,n) for this (i,j)
                pbar.update(base_per_l_n)

    pbar.close()

    # -----------------------------------------------------------------------
    # Aggregate statistics
    # -----------------------------------------------------------------------
    E_arr = np.array(E)
    H_arr = np.array(H)
    SR_arr = E_arr + H_arr

    p_0 = PH[0] / count
    p_1 = PH[1] / count
    p_2 = PH[2] / count
    p_3 = PH[3] / count
    p_4 = PH[4] / count
    p_ge_1 = 1.0 - p_0
    p_ge_2 = 1.0 - (p_0 + p_1)
    expected_failures = sum(i * PH[i] / count for i in range(5))

    q95 = np.quantile(SR_arr, 0.95)
    tail = SR_arr[SR_arr >= q95]
    cvar95 = float(tail.mean()) if tail.size > 0 else float(q95)

    results = {
        "Quarter": quarter_name,
        "Shock": shock,
        "Shock_mult": shock / 442000.0,
        "Cap_pct": max_share_pct,
        "Mean_E": float(E_arr.mean()),
        "Mean_H": float(H_arr.mean()),
        "Mean_SR": float(SR_arr.mean()),
        "Std_SR": float(SR_arr.std()),
        "P_0_banks": p_0,
        "P_1_bank": p_1,
        "P_2_banks": p_2,
        "P_3_banks": p_3,
        "P_4_banks": p_4,
        "P_at_least_1": p_ge_1,
        "P_at_least_2": p_ge_2,
        "Expected_failures": expected_failures,
        "VaR95_SR": float(q95),
        "CVaR95_SR": float(cvar95),
        "N_scenarios": count,
    }

    # Free arrays quickly
    del E_arr, H_arr, SR_arr

    return results


# ---------------------------------------------------------------------------
# Q4 2008 BALANCE-SHEET MATRIX (from your MDPI code, in millions USD)
# ---------------------------------------------------------------------------

MC_Q4_2008 = [
    [144022, 184133,  774185],
    [166884, 341254, 1009277],
    [177052,  92048,  882997],
    [102316,  49433,  781402],
]

SHOCK_BASE = 442000.0  # baseline shock (millions USD)

shock_multipliers = [0.50, 0.75, 1.00, 1.25, 1.50]
cap_grid = [0.25, 0.50]  # 25% vs 50% single-counterparty cap

sensitivity_results = []

print("\n" + "="*80)
print("SENSITIVITY ANALYSIS — Q4 2008 (Shock × Diversification Cap)")
print("="*80)

for cap in cap_grid:
    for mult in shock_multipliers:
        s = SHOCK_BASE * mult
        print(f"\n>>> Running combo: cap={cap*100:.0f}%, shock={mult:.2f}× (s = {s:,.0f}M)")
        res = run_flow_network_quarter_sensitivity(
            MC=MC_Q4_2008,
            shock=s,
            max_share_pct=cap,
            quarter_name="Q4 2008",
            show_progress=True
        )
        sensitivity_results.append(res)

# ---------------------------------------------------------------------------
# Build summary DataFrame
# ---------------------------------------------------------------------------

sens_df = pd.DataFrame(sensitivity_results)

print("\n" + "="*80)
print("SENSITIVITY SUMMARY TABLE — Q4 2008")
print("="*80)

cols_to_show = [
    "Shock_mult", "Cap_pct",
    "Mean_SR", "VaR95_SR", "CVaR95_SR",
    "P_at_least_1", "P_at_least_2", "Expected_failures"
]

print(
    sens_df[cols_to_show]
    .sort_values(["Cap_pct", "Shock_mult"])
    .to_string(
        index=False,
        formatters={
            "Mean_SR":      lambda x: f"{x:,.0f}",
            "VaR95_SR":     lambda x: f"{x:,.0f}",
            "CVaR95_SR":    lambda x: f"{x:,.0f}",
            "P_at_least_1": lambda x: f"{x*100:5.2f}%",
            "P_at_least_2": lambda x: f"{x*100:5.3f}%",
            "Expected_failures": lambda x: f"{x:.3f}",
        }
    )
)

# Save grid to CSV for the paper
sens_df.to_csv("flow_network_sensitivity_Q4_2008.csv", index=False)
print("\n✓ Sensitivity grid exported to: flow_network_sensitivity_Q4_2008.csv")

# ---------------------------------------------------------------------------
# VISUALIZATION: Shock vs Mean SR / P(≥2 failures) for each cap
# ---------------------------------------------------------------------------

fig, axes = plt.subplots(1, 2, figsize=(12, 5), dpi=600)

# Panel 1: Mean SR vs shock multiplier
ax1 = axes[0]
for cap in sorted(cap_grid):
    sub = sens_df[sens_df["Cap_pct"] == cap].sort_values("Shock_mult")
    ax1.plot(
        sub["Shock_mult"],
        sub["Mean_SR"] / 1000.0,
        marker="o", linewidth=2,
        label=f"Cap {int(cap*100)}%"
    )

ax1.set_xlabel("Shock multiplier (relative to baseline s = 442,000M)", fontsize=11, fontweight="bold")
ax1.set_ylabel("Mean Systemic Risk (Billions USD)", fontsize=11, fontweight="bold")
ax1.set_title("Mean Systemic Risk vs Shock Magnitude\n(Q4 2008)", fontsize=12, fontweight="bold")
ax1.grid(True, alpha=0.3, linestyle="--")
ax1.legend(frameon=True, shadow=True)

# Panel 2: P(≥2 failures) vs shock multiplier
ax2 = axes[1]
for cap in sorted(cap_grid):
    sub = sens_df[sens_df["Cap_pct"] == cap].sort_values("Shock_mult")
    ax2.plot(
        sub["Shock_mult"],
        sub["P_at_least_2"] * 100.0,
        marker="s", linewidth=2,
        label=f"Cap {int(cap*100)}%"
    )

ax2.set_xlabel("Shock multiplier (relative to baseline s = 442,000M)", fontsize=11, fontweight="bold")
ax2.set_ylabel("P(≥ 2 failures) [%]", fontsize=11, fontweight="bold")
ax2.set_title("Multi-bank Collapse Probability vs Shock\n(Q4 2008)", fontsize=12, fontweight="bold")
ax2.grid(True, alpha=0.3, linestyle="--")
ax2.legend(frameon=True, shadow=True)

plt.tight_layout()
plt.savefig("Fig_Sensitivity_Q4_2008_Shock_vs_Cap.png", dpi=600, bbox_inches="tight", facecolor="white")
plt.savefig("Fig_Sensitivity_Q4_2008_Shock_vs_Cap.tiff", dpi=600, bbox_inches="tight", facecolor="white")
plt.show()

print("\n✓ Created Fig_Sensitivity_Q4_2008_Shock_vs_Cap.png / .tiff")
print("="*80)
print("Sensitivity analysis complete.")
print("="*80)